# Lista simplificada das ações mais líquidas da B3
LIQUID_STOCKS = [
    "PETR4.SA","VALE3.SA","ITUB4.SA","BBDC4.SA","BBAS3.SA",
    "ABEV3.SA","WEGE3.SA","RENT3.SA","ITSA4.SA","SUZB3.SA",
    "PRIO3.SA","JBSS3.SA","RADL3.SA","LREN3.SA","RAIL3.SA",
    "EQTL3.SA","ELET3.SA","ELET6.SA","GGBR4.SA","CSNA3.SA",
    "USIM5.SA","HAPV3.SA","HYPE3.SA","MULT3.SA","TIMS3.SA",
    "VIVT3.SA","CMIG4.SA","CPLE6.SA","KLBN11.SA","BRFS3.SA",
    "AZUL4.SA","GOLL4.SA","MRVE3.SA","CYRE3.SA","EMBR3.SA",
    "CCRO3.SA","SBSP3.SA","COGN3.SA","TOTS3.SA","DXCO3.SA",
    "B3SA3.SA","FLRY3.SA","BPAC11.SA","ENBR3.SA","ALPA4.SA",
    "BRKM5.SA","GOAU4.SA","IGTI11.SA","CRFB3.SA","PCAR3.SA"
]